elastic:
    hosts: 40.73.68.128:9200,40.73.118.146:9200,139.217.229.245:9200
    scheme: http

mysql:
  host: gz-cdb-7v4po3cb.sql.tencentcdb.com
  port: 62463
  username: do1zt-dev-auth
  password: U2iNo53JlI
  database: do1cloud-dev-sys-auth

spring:
  profiles: local
  elasticsearch:
    rest:
      uris: ${elastic.hosts}
  redis:
    database: 19
    host: 119.29.77.98
    port: 6379
    password: redis@98Do1      # 密码（默认为空）
  cloud:
    consul:
      token: #133ff2f2-32d4-c119-3d54-faf0b461be64
      host: 127.0.0.1 #10.0.5.6
      port: 8500
      discovery:
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 15s
        # 实例ID必须唯一
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}:${server.port}
      config:
         # 是否启动consul的配置管理，默认是true
        enabled: false
sys-auth:
  #项目访问地址(即访问统一认证的地址)
  project-url: http://2x742320d6.qicp.vip:26178
  request-uri:  "@RequestUri"
  callback-base-url: ${sys-auth.request-uri}${server.sys-auth.context-path}

  #token 加密私钥匙
  private-key: MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAmOxxp+qo1uOC4IXToIjfKkttTmZ/Umww1IWAzhyLOs4nF8b0OBKe1va5jdwZvsOU1SWiSLx0Q/nNfGQXh3diQwIDAQABAkAcMJHvA0nmewAYRXMyh6ij0k2vAyP7XKhPtOB+njJoP2lu+5svTCwpVgi+w8bpXjyyM0Oy/NwJl3jtyqLlcyZBAiEAyLQ9MpwHpe0GK0N4sFC5rw0jei+d5gSC4IRdqZXESOMCIQDDDjmh2Oo+qVj1bZMIhgXevKFMQ74N88h/Ta9+BpefIQIgRI8lNIuOJUTxTYgPyxLYSw7O5qcrZe52kqFEqXBqi4cCIQCXJlHQskeq8Q4HebbDlx+7X47ai3AeXbgTtj50uWULIQIgaCwA2tCMnBwoKmTDbfQQDatXWirp0l6j7x6iGKpbgyE=
  #登陆失败时限
  loginFailTime: 1800
  #登陆失败次数
  loginFailNum: 30
  #数据源配置
  data-source:
    # 通讯录数据源
    get-user-info:
      url: http://134.175.141.130:10001
      path: /user/infoByAccount
      by-mobile-path: /user/infoByMobile
      #鉴权后获取用户信息内容字段过滤
      user-info-sensitive-fields: passWord,passwordEncoder
    # 应用数据源
    get-app-info:
      url: http://134.175.141.130:10004
      path: /getAppInfoByAppId
    # 道一中台用户中心
    do1-user-center:
      url: http://134.175.141.130:10001
      get-user-info-path: /user/infoByAccount
      by-mobile-path: /user/infoByMobile
      update-password-path: /user/account/password
      get-user-type-path: /user/getUserType
      save-4a-login-user-path: /user/saveLoginUser
    # 道一统一消息接口
    do1-message:
      url: http://insigeqa.do1zt.xyz:30724/api/message-api
      send-single-sms: /api/sms/send
      send-batch-sms: /api/sms/batch/send
      query-sms-status: /api/sms/status/query

  es:
    user-login-log:
      index: userloginlog
      type: log
    service-auth-log:
      index: serviceauthlog
      type: log
  qw:
    dqsf-share-addressbook:
      url: http://addressbook.qwyqa.do1.work
    dqsf-share-api:
      url: http://api.qwyqa.do1.work
#      url: http://2678s449y4.wicp.vip:20994
    dqsf-share-sys:
      url: http://sys.qwyqa.do1.work
    admin-login-url: ${sys-auth.qw.dqsf-share-sys.url}/micro/sys/auth/authentication.do
    person-login-url: ${sys-auth.qw.dqsf-share-addressbook.url}/micro/addressbook/auth/authentication.do
    public-oauth2-url: ${sys-auth.qw.dqsf-share-addressbook.url}/micro/addressbook/auth/mobileAuthentication.do
    public-qr-admin-url: ${sys-auth.qw.dqsf-share-sys.url}/micro/sys/auth/adminLogin.do
    public-qr-person-url: ${sys-auth.qw.dqsf-share-addressbook.url}/micro/addressbook/auth/personalLogin.do

  # sms配置
  sms-config:
    pass-id: do1cloud-insight
    template-id: 10010010
    sign-id: 100


logging:
  level:
    cn.com.do1.component.gaiasysauth.web.feign.SmsClient: debug


weixin:
  #企业微信公有云
  public:
    server:
      url: https://qyapi.weixin.qq.com/cgi-bin
      access-timeout: 3600
    auth:
      service-url: https://open.work.weixin.qq.com
      web-url: ${weixin.public.auth.service-url}/connect/oauth2/authorize?appid=%s&redirect_uri=%s&response_type=%s&scope=%s&state=%s#wechat_redirect
      #自建应用
      web-self-built-url: ${weixin.public.auth.service-url}/connect/oauth2/authorize?appid=%s&redirect_uri=%s&agentid=%s&response_type=%s&scope=%s&state=%s#wechat_redirect
      web-callback-url: ${sys-auth.callback-base-url}/wxOauthAuthCallBack
      qr-url: ${weixin.public.auth.service-url}/wwopen/sso/3rd_qrConnect?appid=%s&state=%s&usertype=%s&redirect_uri=%s
      qr-callback-url:  ${sys-auth.callback-base-url}/wxQrAuthCallBack
 #企业微信私有化
  private:
    server:
      access-timeout: 3600
      url: http://qywx.qiweioa.cn/cgi-bin
      corp-id: wwe67a3a6c53fdb3e2
      message:
        token: cbgci2EzJbviTsPGZYNn07Q5VM
        aesKey: X8oMz6pCuTdpj7mFhl5zXjszlPpWP8Bx9chWtFqOFe1
      login:
        token: 4iDes6YodGao7n07L6GgtvEyWVqWHbVf
        aesKey: VFi2dTHH7xnJ84CVIbiUFezl1tCg383EgIqAb81hwLV
    auth:
      web-url: http://qywx.qiweioa.cn/connect/oauth2/authorize?appid=%s&redirect_uri=%s&response_type=code&scope=%s&agentid=%s&state=STATE#wechat_redirect
      qr-url: http://qywx.qiweioa.cn/wwopen/sso/qrConnect?appid=%s&redirect_uri=%s&agentid=%s&state=web_login@gyoss9
      callback-url:  ${sys-auth.callback-base-url}/wxPrivateAuthCallBack
  qw:
    public:
      auth:
        corp-id: ww9b9ddee6b3b9b8ac
        qr-callback-url:  ${sys-auth.callback-base-url}/handleWeixinQrCode.do
        web-callback-url:  ${sys-auth.callback-base-url}/handleWeixinWebCode.do

